# Generated by Django 5.0 on 2023-12-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_discount_tax_item_currency_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='amount',
        ),
        migrations.AddField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.FloatField(default=13.0),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_name',
            field=models.CharField(default='NDFL', max_length=255),
        ),
    ]
