# Generated by Django 5.0 on 2023-12-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_tax_amount_tax_inclusive_tax_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='duration',
            field=models.CharField(default='once', max_length=255),
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_name',
            field=models.CharField(default='VAT', max_length=255),
        ),
    ]
